import { FESTIVAL_STATUS } from '@/lib/constants';

export const mockFestivals = [
  {
    id: 'f1',
    title: 'Java Jazz Festival 2026',
    slug: 'java-jazz-festival-2026',
    artist: 'Guns N Roses',
    lineup: ['Guns N Roses', 'Musisi Jazz Nasional', 'Musisi Jazz Internasional'],
    genre: 'Jazz',
    date: '2026-05-15T14:00:00Z',
    endDate: '2026-05-17T23:00:00Z',
    venue: 'JIExpo Kemayoran',
    city: 'DKI Jakarta',
    province: 'Jakarta',
    priceStart: 350000,
    image: 'https://dynamicmedia.livenationinternational.com/e/m/k/4f5826ee-8f2d-4d6c-b64f-3c642549e385.png',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: true,
    organizerId: 'org1',
    description: 'Java Jazz Festival 2026 kembali hadir lebih spektakuler dengan Guns N Roses sebagai headliner! Festival musik terbesar di Asia Tenggara ini akan memanjakan penonton dengan penampilan legendaris dan ratusan musisi papan atas.',
    schedule: [
      { time: '2026-05-15T14:00:00Z', title: 'Main Stage: Guns N Roses' },
      { time: '2026-05-15T18:00:00Z', title: 'Jazz Lounge Session' },
      { time: '2026-05-16T15:00:00Z', title: 'International Jazz Showcase' },
      { time: '2026-05-17T16:00:00Z', title: 'Grand Closing' },
    ],
    organizer: {
      name: 'Java Festival Production',
      description: 'Perusahaan penyelenggara festival musik premium di Indonesia sejak 2005.',
    },
    faq: [
      { q: 'Apakah anak-anak boleh masuk?', a: 'Anak-anak di atas 5 tahun diperbolehkan masuk dengan tiket masuk.' },
      { q: 'Apakah tersedia area parkir?', a: 'Tersedia area parkir yang luas di kompleks JIExpo.' },
      { q: 'Apakah tiket bisa refund?', a: 'Tiket yang sudah dibeli tidak dapat direfund kecuali event dibatalkan.' },
    ],
    rules: [
      'Dilarang membawa makanan dan minuman dari luar',
      'Dilarang membawa kamera profesional',
      'Anak di bawah 5 tahun tidak diperbolehkan masuk',
      'Dilarang membawa benda tajam',
      'Dilarang melakukan re-sale tiket di luar platform resmi',
    ],
    ticketTypes: [
      { id: 'f1t1', name: 'VIP', price: 1500000, quota: 200, sold: 150 },
      { id: 'f1t2', name: 'Category 1', price: 850000, quota: 500, sold: 400 },
      { id: 'f1t3', name: 'Category 2', price: 500000, quota: 1000, sold: 600 },
      { id: 'f1t4', name: 'Festival', price: 350000, quota: 2000, sold: 1200 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-05-14T23:59:59Z' },
    views: 12450,
  },
  {
    id: 'f2',
    title: 'Coldplay: Music of the Spheres',
    slug: 'coldplay-music-of-the-spheres',
    artist: 'Coldplay',
    lineup: ['Coldplay', 'Special Guest'],
    genre: 'Pop',
    date: '2026-06-20T19:30:00Z',
    endDate: '2026-06-20T22:30:00Z',
    venue: 'Gelora Bung Karno',
    city: 'DKI Jakarta',
    province: 'Jakarta',
    priceStart: 850000,
    image: 'https://dynamicmedia.livenationinternational.com/b/z/w/1f16b59d-09c9-432d-ad90-39fcc1a6f25a.jpg',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'sold_out',
    featured: true,
    organizerId: 'org2',
    description: 'Coldplay kembali ke Indonesia lewat tur dunia Music of the Spheres! Pertunjukan penuh visual spektakuler, lagu-lagu ikonik, dan pengalaman konser yang tak terlupakan di Gelora Bung Karno.',
    schedule: [
      { time: '2026-06-20T17:00:00Z', title: 'Gates Open' },
      { time: '2026-06-20T19:30:00Z', title: 'Coldplay On Stage' },
    ],
    organizer: {
      name: 'Live Nation Indonesia',
      description: 'Bagian dari Live Nation Entertainment, jaringan promotor konser global terbesar.',
    },
    faq: [
      { q: 'Apakah tiket masih tersedia?', a: 'Maaf, seluruh tiket untuk konser ini sudah habis terjual.' },
      { q: 'Apakah tersedia tribune?', a: 'Seluruh kategori tiket menggunakan standing area di lapangan GBK.' },
    ],
    rules: [
      'Dilarang membawa kamera profesional',
      'Dilarang membawa drone',
      'Xylobands disediakan oleh panitia',
    ],
    ticketTypes: [
      { id: 'f2t1', name: 'Ultimate', price: 2500000, quota: 500, sold: 500 },
      { id: 'f2t2', name: 'CAT 1', price: 1500000, quota: 1500, sold: 1500 },
      { id: 'f2t3', name: 'CAT 2', price: 850000, quota: 3000, sold: 3000 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-06-19T23:59:59Z' },
    views: 9850,
  },
  {
    id: 'f3',
    title: 'Festival Musik Indonesia 2026',
    slug: 'festival-musik-indonesia-2026',
    artist: 'Backstreet Boys',
    lineup: ['Backstreet Boys', 'Penampil Lokal', 'DJ Performance'],
    genre: 'Pop',
    date: '2026-07-03T13:00:00Z',
    endDate: '2026-07-05T22:00:00Z',
    venue: 'Lapangan Rampal',
    city: 'Malang',
    province: 'Jawa Timur',
    priceStart: 200000,
    image: 'https://dynamicmedia.livenationinternational.com/t/r/j/4ff345c9-05b8-455b-9970-900cc6a6320e.jpg?format=webp&width=1080&quality=75',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: true,
    organizerId: 'org3',
    description: 'Festival Musik Indonesia 2026 menghadirkan Backstreet Boys sebagai bintang utama! Tiga hari penuh musik, panggung megah, dan penampil yang tak boleh dilewatkan di Lapangan Rampal.',
    schedule: [
      { time: '2026-07-03T13:00:00Z', title: 'Opening Day' },
      { time: '2026-07-04T15:00:00Z', title: 'Backstreet Boys Main Performance' },
      { time: '2026-07-05T16:00:00Z', title: 'Closing Festival' },
    ],
    organizer: {
      name: 'RAJ Productions',
      description: 'Event organizer musik ternama dengan pengalaman mengelola festival skala nasional.',
    },
    faq: [
      { q: 'Apakah area VIP dekat dengan panggung?', a: 'Ya, area VIP berada paling dekat dengan panggung utama.' },
      { q: 'Berapa durasi festival setiap harinya?', a: 'Festival berlangsung dari siang hingga malam setiap harinya.' },
    ],
    rules: ['Tidak ada kursi untuk area festival', 'Dilarang membawa makanan dari luar'],
    ticketTypes: [
      { id: 'f3t1', name: 'VIP', price: 750000, quota: 1000, sold: 700 },
      { id: 'f3t2', name: 'Reguler', price: 350000, quota: 3000, sold: 2000 },
      { id: 'f3t3', name: 'Early Bird', price: 200000, quota: 2000, sold: 2000 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-07-02T23:59:59Z' },
    views: 8200,
  },
  {
    id: 'f4',
    title: 'Michael Learns To Rock Reunion Tour',
    slug: 'michael-learns-to-rock-reunion-tour',
    artist: 'Michael Learns To Rock',
    lineup: ['Michael Learns To Rock', 'Opening Act'],
    genre: 'Pop',
    date: '2026-08-12T19:00:00Z',
    endDate: '2026-08-12T22:00:00Z',
    venue: 'Stadion Utama GBK',
    city: 'DKI Jakarta',
    province: 'Jakarta',
    priceStart: 500000,
    image: 'https://dynamicmedia.livenationinternational.com/d/q/q/97fa78ed-62e1-4f35-ab15-ccd9ee3d2545.jpg?format=webp&width=1080&quality=75',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: false,
    organizerId: 'org2',
    description: 'Legenda musik pop Michael Learns To Rock kembali tampil dalam Reunion Tour! Saksikan lagu-lagu hits era 90-an seperti That\'s Why You Go Away dan Paint My Love secara live.',
    schedule: [
      { time: '2026-08-12T17:00:00Z', title: 'Gates Open' },
      { time: '2026-08-12T19:00:00Z', title: 'MLTR On Stage' },
    ],
    organizer: {
      name: 'Live Nation Indonesia',
      description: 'Bagian dari Live Nation Entertainment, jaringan promotor konser global terbesar.',
    },
    faq: [
      { q: 'Apakah tersedia kursi?', a: 'Kategori VIP dan CAT 1 menggunakan kursi bernomor, CAT 2 standing area.' },
      { q: 'Kapan pintu dibuka?', a: 'Pintu dibuka pukul 17.00 WIB, konser dimulai pukul 19.00 WIB.' },
    ],
    rules: ['Dilarang membawa kamera profesional', 'Tidak ada kursi disediakan untuk CAT 2'],
    ticketTypes: [
      { id: 'f4t1', name: 'VIP', price: 1500000, quota: 500, sold: 300 },
      { id: 'f4t2', name: 'CAT 1', price: 900000, quota: 1000, sold: 650 },
      { id: 'f4t3', name: 'CAT 2', price: 500000, quota: 2000, sold: 1100 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-08-11T23:59:59Z' },
    views: 6400,
  },
  {
    id: 'f5',
    title: 'Hindia: The Tour 2026',
    slug: 'hindia-the-tour-2026',
    artist: 'Hindia',
    lineup: ['Hindia', 'Special Guest'],
    genre: 'Indie',
    date: '2026-08-28T19:30:00Z',
    endDate: '2026-08-28T22:30:00Z',
    venue: 'Balai Sarbini',
    city: 'DKI Jakarta',
    province: 'Jakarta',
    priceStart: 400000,
    image: 'https://hindia.id/archive/hd2.jpg',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: false,
    organizerId: 'org4',
    description: 'Hindia membawa tur tunggalnya The Tour 2026! Malam penuh musik, lirik mendalam, dan energi khas Hindia yang menghipnotis penonton di Balai Sarbini.',
    schedule: [
      { time: '2026-08-28T18:00:00Z', title: 'Gates Open' },
      { time: '2026-08-28T19:30:00Z', title: 'Hindia On Stage' },
    ],
    organizer: {
      name: 'Sena Didi Mulyadi',
      description: 'Promotor yang berfokus pada musisi indie dan alternatif Indonesia.',
    },
    faq: [
      { q: 'Apakah konser menggunakan kursi?', a: 'Area VIP bersebelahan dengan panggung, area festival standing.' },
      { q: 'Apakah boleh membawa kamera?', a: 'Kamera saku diperbolehkan, kamera profesional tidak diizinkan.' },
    ],
    rules: ['Kamera saku diperbolehkan', 'Dilarang membawa minuman beralkohol'],
    ticketTypes: [
      { id: 'f5t1', name: 'VIP', price: 750000, quota: 300, sold: 200 },
      { id: 'f5t2', name: 'Festival', price: 400000, quota: 800, sold: 500 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-08-27T23:59:59Z' },
    views: 5100,
  },
  {
    id: 'f6',
    title: 'God Bless: Rockin\' the Nation',
    slug: 'god-bless-rockin-the-nation',
    artist: 'God Bless',
    lineup: ['God Bless', 'Ahmad Albar', 'Eross Candra', 'Special Guest'],
    genre: 'Rock',
    date: '2026-09-05T19:00:00Z',
    endDate: '2026-09-05T23:00:00Z',
    venue: 'Lapangan Gasibu',
    city: 'Bandung',
    province: 'Jawa Barat',
    priceStart: 150000,
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/God_Bless_2020_stamp_of_Indonesia.jpg',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: false,
    organizerId: 'org5',
    description: 'God Bless, legenda rock Indonesia, kembali menggelegar lewat konser Rockin\' the Nation! Persembahan spesial untuk para penggemar setia rock n roll Tanah Air.',
    schedule: [
      { time: '2026-09-05T19:00:00Z', title: 'God Bless On Stage' },
    ],
    organizer: {
      name: 'Festival Rock Produksi',
      description: 'Promotor khusus genre rock dan metal di Indonesia.',
    },
    faq: [
      { q: 'Apakah anak-anak diperbolehkan?', a: 'Boleh, namun wajib didampingi orang tua.' },
      { q: 'Apakah tersedia area VIP dekat panggung?', a: 'Ya, area VIP paling dekat dengan panggung utama.' },
    ],
    rules: ['Anak-anak wajib didampingi orang tua', 'Dilarang membawa benda berbahaya'],
    ticketTypes: [
      { id: 'f6t1', name: 'VIP', price: 350000, quota: 500, sold: 320 },
      { id: 'f6t2', name: 'Festival', price: 150000, quota: 2000, sold: 1200 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-09-04T23:59:59Z' },
    views: 3400,
  },
  {
    id: 'f7',
    title: 'Ifan Seventeen: The Last Chapter',
    slug: 'ifan-seventeen-the-last-chapter',
    artist: 'Ifan Seventeen',
    lineup: ['Ifan Seventeen', 'Orchestra Live'],
    genre: 'Pop',
    date: '2026-09-18T19:30:00Z',
    endDate: '2026-09-18T22:00:00Z',
    venue: 'Ciputra Artpreneur',
    city: 'DKI Jakarta',
    province: 'Jakarta',
    priceStart: 550000,
    image: 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Jakarta/o/1740326465552-FOTO_IFAN_NEW_2/oxyn9qzdmij8656.jpeg',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'sold_out',
    featured: false,
    organizerId: 'org6',
    description: 'Ifan Seventeen menutup babak terakhir perjalanan musiknya lewat The Last Chapter. Malam penuh haru dengan lagu-lagu ikonik yang menemani perjalanan banyak orang.',
    schedule: [
      { time: '2026-09-18T19:30:00Z', title: 'Ifan Seventeen On Stage' },
    ],
    organizer: {
      name: 'Denganmu Production',
      description: 'EO yang menghadirkan konser-konser intim dengan nuansa orkestra.',
    },
    faq: [
      { q: 'Apakah tiket masih tersedia?', a: 'Maaf, seluruh tiket untuk konser ini sudah habis terjual.' },
      { q: 'Apakah ada orkestra live?', a: 'Ya, konser ini diiringi orkestra live yang menambah kesan dramatis.' },
    ],
    rules: ['Dress code: Smart Casual', 'Dilarang membawa makanan dari luar'],
    ticketTypes: [
      { id: 'f7t1', name: 'VIP', price: 1200000, quota: 400, sold: 400 },
      { id: 'f7t2', name: 'CAT 1', price: 850000, quota: 700, sold: 700 },
      { id: 'f7t3', name: 'CAT 2', price: 550000, quota: 1200, sold: 1200 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-09-17T23:59:59Z' },
    views: 2900,
  },
  {
    id: 'f8',
    title: 'Enau Festival 2026',
    slug: 'enau-festival-2026',
    artist: 'Enau',
    lineup: ['Enau', 'Penampil Lokal', 'DJ Performance'],
    genre: 'EDM',
    date: '2026-10-02T15:00:00Z',
    endDate: '2026-10-02T23:00:00Z',
    venue: 'Stadion Batakan',
    city: 'Balikpapan',
    province: 'Kalimantan Timur',
    priceStart: 250000,
    image: 'https://cdn.medcom.id/dynamic/content/2024/11/22/1730140/7qrnEDxdyu.jpg?w=1024',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'available',
    featured: false,
    organizerId: 'org7',
    description: 'Enau Festival 2026 kembali hadir di Kalimantan! Festival musik tahunan dengan lineup terbaik, panggung megah, dan suasana konser yang meriah di Stadion Batakan.',
    schedule: [
      { time: '2026-10-02T15:00:00Z', title: 'Opening Day' },
      { time: '2026-10-02T20:00:00Z', title: 'Headline Performance' },
    ],
    organizer: {
      name: 'Kaltim Event Organizer',
      description: 'EO lokal Kalimantan yang mengembangkan scene festival musik di Indonesia Timur.',
    },
    faq: [
      { q: 'Berapa lama festival berlangsung?', a: 'Festival dimulai siang hari dan berakhir menjelang tengah malam.' },
      { q: 'Apakah tersedia penginapan?', a: 'Area sekitar Stadion Batakan memiliki banyak pilihan penginapan.' },
    ],
    rules: ['Dilarang membawa kamera profesional', 'Dilarang membawa minuman beralkohol'],
    ticketTypes: [
      { id: 'f8t1', name: 'VIP', price: 600000, quota: 800, sold: 400 },
      { id: 'f8t2', name: 'Reguler', price: 350000, quota: 2500, sold: 1500 },
      { id: 'f8t3', name: 'Early Bird', price: 250000, quota: 1500, sold: 1500 },
    ],
    salesPeriod: { start: '2026-01-01T00:00:00Z', end: '2026-10-01T23:59:59Z' },
    views: 4500,
  },
  {
    id: 'f9',
    title: 'Pameran Soundrenaline 2026',
    slug: 'soundrenaline-2026',
    artist: 'Special Guest',
    lineup: ['Tomorrow X Together', 'Indie Bands'], 
    genre: 'Rock',
    date: '2026-11-14T12:00:00Z',
    endDate: '2026-11-15T23:00:00Z',
    venue: 'Eks Pasar Proyek',
    city: 'Cibubur',
    province: 'DKI Jakarta',
    priceStart: 300000,
    image: 'https://dynamicmedia.livenationinternational.com/o/o/d/d9f0f8ac-61a7-47b6-b05d-728f5a5e8234.jpg',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'coming_soon',
    featured: false,
    organizerId: 'org2',
    description: 'Soundrenaline kembali hadir dengan format baru yang lebih intelektual dan berakar pada budaya Indonesia! Dua hari penuh penampilan musik terbaik dan artwork yang memukau.',
    schedule: [
      { time: '2026-11-14T12:00:00Z', title: 'Day 1' },
      { time: '2026-11-15T12:00:00Z', title: 'Day 2' },
    ],
    organizer: {
      name: 'Live Nation Indonesia',
      description: 'Bagian dari Live Nation Entertainment, jaringan promotor konser global terbesar.',
    },
    faq: [
      { q: 'Kapan tiket mulai dijual?', a: 'Tiket akan mulai dijual dalam waktu dekat. Nantikan pengumuman resmi.' },
    ],
    rules: ['Dilarang membawa kamera profesional', 'Dilarang membawa benda berbahaya'],
    ticketTypes: [
      { id: 'f9t1', name: 'Festival 2 Days', price: 500000, quota: 2000, sold: 0 },
      { id: 'f9t2', name: 'Day 1 Only', price: 300000, quota: 1500, sold: 0 },
    ],
    salesPeriod: { start: '2026-10-01T00:00:00Z', end: '2026-11-13T23:59:59Z' },
    views: 1500,
  },
  {
    id: 'f10',
    title: 'Ladiesrock Festival 2026',
    slug: 'ladiesrock-festival-2026',
    artist: 'Special Guest',
    lineup: ['Voice of Baceprot', 'Mona Risakotta'],
    genre: 'Rock',
    date: '2026-12-05T13:00:00Z',
    endDate: '2026-12-05T23:00:00Z',
    venue: 'Jatim Expo',
    city: 'Surabaya',
    province: 'Jawa Timur',
    priceStart: 280000,
    image: 'https://i0.wp.com/jatimtimes.com/storage/news/191208093649-07-raja.jpg?quality=80&w=1200&h=700&fit=crop',
    status: FESTIVAL_STATUS.PUBLISHED,
    ticketStatus: 'coming_soon',
    featured: false,
    organizerId: 'org8',
    description: 'Ladiesrock Festival kembali hadir dengan lineup kekuatan perempuan rock Indonesia yang mengguncang panggung Jatim Expo Surabaya!',
    schedule: [
      { time: '2026-12-05T13:00:00Z', title: 'Opening Performance' },
      { time: '2026-12-05T19:00:00Z', title: 'Headline Performance' },
    ],
    organizer: {
      name: 'Jatim Event Production',
      description: 'EO yang fokus mengangkat musisi perempuan dan genre rock di Jawa Timur.',
    },
    faq: [
      { q: 'Apakah tiket sudah dijual?', a: 'Tiket akan mulai dijual dalam waktu dekat.' },
    ],
    rules: ['Anak di bawah 12 tahun wajib didampingi', 'Tidak ada kursi untuk area festival'],
    ticketTypes: [
      { id: 'f10t1', name: 'VIP', price: 550000, quota: 600, sold: 0 },
      { id: 'f10t2', name: 'Festival', price: 280000, quota: 2000, sold: 0 },
    ],
    salesPeriod: { start: '2026-10-15T00:00:00Z', end: '2026-12-04T23:59:59Z' },
    views: 900,
  },
];

export const mockUsers = [
  {
    id: 'u1',
    name: 'Admin',
    email: 'admin@conserid.com',
    phone: '081234567890',
    role: 'admin',
    password: 'Admin123',
  },
  {
    id: 'u2',
    name: 'Organizer',
    email: 'organizer@conserid.com',
    phone: '081234567891',
    role: 'organizer',
    password: 'Organizer123',
  },
  {
    id: 'u3',
    name: 'Customer',
    email: 'customer@conserid.com',
    phone: '081234567892',
    role: 'customer',
    password: 'Customer123',
  },
];

export const mockOrganizers = [
  { id: 'org1', name: 'Java Festival Production', email: 'java@festival.id', festivals: ['f1'] },
  { id: 'org2', name: 'Live Nation Indonesia', email: 'contact@livenation.id', festivals: ['f2', 'f4', 'f9'] },
  { id: 'org3', name: 'RAJ Productions', email: 'raj@productions.id', festivals: ['f3'] },
  { id: 'org4', name: 'Sena Didi Mulyadi', email: 'sena@dm.id', festivals: ['f5'] },
  { id: 'org5', name: 'Festival Rock Produksi', email: 'rock@festival.id', festivals: ['f6'] },
  { id: 'org6', name: 'Denganmu Production', email: 'denganmu@prod.id', festivals: ['f7'] },
  { id: 'org7', name: 'Kaltim Event Organizer', email: 'kaltim@eo.id', festivals: ['f8'] },
  { id: 'org8', name: 'Jatim Event Production', email: 'jatim@eo.id', festivals: ['f10'] },
];